# Generated by Django 6.0.1 on 2026-01-10 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owners',
            field=models.ManyToManyField(related_name='cars', through='project_first_app.Ownership', through_fields=('id_car', 'id_owner'), to='project_first_app.carowner'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='id_car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='project_first_app.car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownership',
            name='id_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='project_first_app.carowner'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.UniqueConstraint(fields=('id_owner', 'id_car', 'start_date'), name='unique_ownership'),
        ),
    ]
